[package]
name = "kvs"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.32.0"
serde = "1.0.193"
serde_json = "1.0.108"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
